"""Generated SDK build and boundary checks."""

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


def test_sdk_typecheck_passes_with_pinned_node_tooling() -> None:
    completed = subprocess.run(
        ["npm", "run", "typecheck:harness-sdk"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr


def test_sdk_uses_generated_contracts_without_any() -> None:
    declaration = (
        ROOT / "generated/harness/protocol/atlas-harness.d.ts"
    ).read_text()
    package = json.loads((ROOT / "package.json").read_text())
    assert "Generated by scripts/generate_harness_protocol.py" in declaration
    assert ": any" not in declaration
    assert "typecheck:harness-sdk" in package["scripts"]
