"""Validated and bounded Atlas Harness task scheduling."""

from app.services.harness.protocol.background_job_execution import (
    BackgroundJobArtifactWriter,
    BackgroundJobCoordinatorError,
    BackgroundJobCoordinatorErrorCode,
    BackgroundJobExecutionResult,
    BackgroundJobExecutor,
    BackgroundJobStore,
)
from app.services.harness.protocol.background_jobs import (
    BACKGROUND_JOB_TRANSITIONS,
    MAXIMUM_AGGREGATE_BACKGROUND_JOB_BYTES,
    MAXIMUM_BACKGROUND_JOB_ARGUMENT_BYTES,
    MAXIMUM_BACKGROUND_JOB_BYTES,
    MAXIMUM_BACKGROUND_JOB_PAGE,
    MAXIMUM_BACKGROUND_JOBS,
    TERMINAL_BACKGROUND_JOB_STATES,
    BackgroundJobArtifact,
    BackgroundJobConfiguration,
    BackgroundJobPage,
    BackgroundJobRecord,
    BackgroundJobState,
    JobExecutionOwnerId,
    require_background_job_transition,
)
from app.services.harness.scheduler.coordinator import BackgroundJobCoordinator
from app.services.harness.scheduler.dag import (
    DagCompilation,
    DagCompileError,
    DagNodeSpec,
    TaskGraphDefinition,
    compile_task_graph,
    ready_task_ids,
    task_graph_sha256,
)
from app.services.harness.scheduler.durable import (
    DagLease,
    DagNodeRecord,
    DagNodeStatus,
    DagStoreConflict,
    DurableDagScheduler,
    DurableDagStore,
    InMemoryDurableDagStore,
)
from app.services.harness.scheduler.recovery import (
    DagReconciliation,
    DagRecoveryAction,
    DagRecoveryEvidence,
    DagWorkerObservation,
    DagWorkerOutcome,
    DurableDagRecoveryCoordinator,
    InMemoryRecoverableDagStore,
    RecoverableDagStore,
    build_dag_recovery_evidence,
    dag_recovery_evidence_sha256,
)

__all__ = (
    "BACKGROUND_JOB_TRANSITIONS",
    "MAXIMUM_AGGREGATE_BACKGROUND_JOB_BYTES",
    "MAXIMUM_BACKGROUND_JOB_ARGUMENT_BYTES",
    "MAXIMUM_BACKGROUND_JOB_BYTES",
    "MAXIMUM_BACKGROUND_JOB_PAGE",
    "MAXIMUM_BACKGROUND_JOBS",
    "TERMINAL_BACKGROUND_JOB_STATES",
    "BackgroundJobArtifact",
    "BackgroundJobArtifactWriter",
    "BackgroundJobConfiguration",
    "BackgroundJobCoordinator",
    "BackgroundJobCoordinatorError",
    "BackgroundJobCoordinatorErrorCode",
    "BackgroundJobExecutionResult",
    "BackgroundJobExecutor",
    "BackgroundJobPage",
    "BackgroundJobRecord",
    "BackgroundJobState",
    "JobExecutionOwnerId",
    "BackgroundJobStore",
    "DagCompilation",
    "DagCompileError",
    "DagNodeSpec",
    "TaskGraphDefinition",
    "compile_task_graph",
    "ready_task_ids",
    "task_graph_sha256",
    "DagLease",
    "DagNodeRecord",
    "DagNodeStatus",
    "DagStoreConflict",
    "DurableDagScheduler",
    "DurableDagStore",
    "InMemoryDurableDagStore",
    "DagRecoveryAction",
    "DagRecoveryEvidence",
    "DagReconciliation",
    "DagWorkerObservation",
    "DagWorkerOutcome",
    "DurableDagRecoveryCoordinator",
    "InMemoryRecoverableDagStore",
    "RecoverableDagStore",
    "build_dag_recovery_evidence",
    "dag_recovery_evidence_sha256",
    "require_background_job_transition",
)
