import hashlib
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

from scripts.verify_harness_generated_artifacts import (
    GeneratedArtifactError,
    validate_generated_artifacts,
)
from scripts.verify_harness_packages import (
    PackageVerificationError,
    validate_wheel,
)
from scripts.verify_harness_sbom import SbomError, validate_sbom

ROOT = Path(__file__).resolve().parents[1]


def test_checked_in_generated_manifest_passes_real_cli() -> None:
    result = subprocess.run(
        [sys.executable, "scripts/verify_harness_generated_artifacts.py"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == "Generated-artifact manifest valid: 2 artifacts"


def test_hand_edited_generated_artifact_is_rejected(tmp_path: Path) -> None:
    generated = tmp_path / "schema.json"
    generated.write_text(
        "// Generated by fixture\n{}\n",
        encoding="utf-8",
    )
    original_digest = hashlib.sha256(generated.read_bytes()).hexdigest()
    manifest = {
        "schema_version": 1,
        "artifacts": [
            {
                "path": "schema.json",
                "generator": "fixture-generator",
                "marker": "Generated by fixture",
                "sha256": original_digest,
            }
        ],
    }
    generated.write_text(
        "// Generated by fixture\n{\"edited\": true}\n",
        encoding="utf-8",
    )

    with pytest.raises(GeneratedArtifactError, match="digest changed"):
        validate_generated_artifacts(tmp_path, manifest)


def valid_sbom() -> dict[str, object]:
    return {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "version": 1,
        "metadata": {
            "component": {
                "name": "rag-api",
                "version": "0.1.0",
                "bom-ref": "rag-api@0.1.0",
            }
        },
        "components": [
            {
                "name": "example",
                "version": "1.0.0",
                "bom-ref": "example@1.0.0",
                "purl": "pkg:pypi/example@1.0.0",
            }
        ],
        "dependencies": [
            {"ref": "rag-api@0.1.0", "dependsOn": ["example@1.0.0"]},
            {"ref": "example@1.0.0", "dependsOn": []},
        ],
    }


def test_sbom_unknown_dependency_is_rejected() -> None:
    document = valid_sbom()
    document["dependencies"][0]["dependsOn"].append("unknown@1.0.0")

    with pytest.raises(SbomError, match="unknown component"):
        validate_sbom(document)


def test_sbom_accepts_locked_npm_build_dependency() -> None:
    document = valid_sbom()
    document["components"].append(
        {
            "name": "typescript",
            "version": "6.0.3",
            "bom-ref": "npm:typescript@6.0.3",
            "purl": "pkg:npm/typescript@6.0.3",
        }
    )
    document["dependencies"][0]["dependsOn"].append(
        "npm:typescript@6.0.3"
    )
    document["dependencies"].append(
        {"ref": "npm:typescript@6.0.3", "dependsOn": []}
    )

    assert validate_sbom(document) == (2, 3)


def test_sbom_rejects_unsupported_package_ecosystem() -> None:
    document = valid_sbom()
    document["components"][0]["purl"] = "pkg:generic/example@1.0.0"

    with pytest.raises(SbomError, match="unsupported SBOM package URL"):
        validate_sbom(document)


def test_wheel_without_notice_is_rejected(tmp_path: Path) -> None:
    wheel_path = tmp_path / "fixture.whl"
    with zipfile.ZipFile(wheel_path, "w") as archive:
        archive.writestr("app/services/harness/__init__.py", "")

    with pytest.raises(PackageVerificationError, match="omits.*notice"):
        validate_wheel(wheel_path, maximum_bytes=1024)
