import json
import subprocess
import sys
from pathlib import Path

from jsonschema import Draft202012Validator

from scripts.generate_harness_protocol import (
    CURRENT_SCHEMA_VERSION,
    MANIFEST_PATH,
    PROTOCOL_MODELS,
    SCHEMA_PATH,
    TYPESCRIPT_PATH,
)
from scripts.harness_protocol_fixtures import FIXTURE_PATHS

ROOT = Path(__file__).resolve().parents[1]


def test_checked_in_protocol_artifacts_match_clean_generation() -> None:
    result = subprocess.run(
        [
            sys.executable,
            "scripts/generate_harness_protocol.py",
            "--check",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        timeout=90,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.strip().endswith(
        f"schema {CURRENT_SCHEMA_VERSION}, {len(PROTOCOL_MODELS)} roots"
    )


def test_generated_json_schema_is_valid_and_complete() -> None:
    schema = json.loads((ROOT / SCHEMA_PATH).read_text(encoding="utf-8"))

    Draft202012Validator.check_schema(schema)
    assert schema["x-atlas-schema-version"] == CURRENT_SCHEMA_VERSION
    assert len(schema["x-atlas-root-models"]) == len(PROTOCOL_MODELS)
    assert len(schema["x-atlas-command-contracts"]) == 21
    assert "CommandEnvelope" in schema["$defs"]
    assert "EventRecord" in schema["$defs"]


def test_generated_typescript_is_strict_and_marked() -> None:
    declarations = (ROOT / TYPESCRIPT_PATH).read_text(encoding="utf-8")

    assert declarations.startswith(
        "// Generated by scripts/generate_harness_protocol.py"
    )
    assert "export interface CommandEnvelope" in declarations
    assert "export interface EventRecord" in declarations
    assert ": any" not in declarations
    assert " any" not in declarations
    assert "[k: string]" not in declarations


def test_generated_typescript_passes_pinned_strict_compiler() -> None:
    result = subprocess.run(
        ["npm", "run", "typecheck:harness-protocol"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        timeout=90,
    )

    assert result.returncode == 0, result.stdout + result.stderr


def test_generated_manifest_tracks_only_public_contract_artifacts() -> None:
    manifest = json.loads((ROOT / MANIFEST_PATH).read_text(encoding="utf-8"))
    tracked_paths = {
        artifact["path"] for artifact in manifest["artifacts"]
    }

    assert tracked_paths == {
        SCHEMA_PATH.as_posix(),
        TYPESCRIPT_PATH.as_posix(),
    }
    assert all((ROOT / fixture_path).is_file() for fixture_path in FIXTURE_PATHS)
