#!/usr/bin/env node

import process from "node:process";

import { compile } from "json-schema-to-typescript";

const inputChunks = [];
for await (const inputChunk of process.stdin) {
  inputChunks.push(inputChunk);
}

const schema = JSON.parse(Buffer.concat(inputChunks).toString("utf8"));
const banner = [
  "// Generated by scripts/generate_harness_protocol.py",
  "// json-schema-to-typescript@15.0.4; DO NOT EDIT.",
].join("\n");
const declarations = await compile(schema, "AtlasHarnessProtocol", {
  additionalProperties: false,
  bannerComment: banner,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  format: true,
  style: {
    bracketSpacing: true,
    printWidth: 88,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
  unreachableDefinitions: true,
});

process.stdout.write(declarations.replaceAll("\r\n", "\n"));
