#!/usr/bin/env python3
"""Generate and byte-check Atlas Harness JSON Schema and TypeScript contracts."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Mapping
from pathlib import Path

from pydantic import BaseModel
from pydantic.json_schema import models_json_schema

from app.services.harness.protocol import (
    COMMAND_CONTRACTS,
    ApprovalRecord,
    ArtifactRecord,
    CanonicalEventType,
    CommandContract,
    CommandEnvelope,
    ContextManifest,
    EvaluationRunRecord,
    EventRecord,
    GrantRecord,
    ItemRecord,
    OperationRecord,
    PageInfo,
    PolicyDecisionRecord,
    PrincipalRecord,
    ProviderRouteDecisionRecord,
    TaskNodeRecord,
    ThreadRecord,
    TurnRecord,
    WorkspaceRecord,
)

ROOT = Path(__file__).resolve().parents[1]
CURRENT_SCHEMA_VERSION = "1.2"
GENERATOR_VERSION = "json-schema-to-typescript@15.0.4"
GENERATOR_MARKER = (
    "Generated by scripts/generate_harness_protocol.py; DO NOT EDIT."
)
SCHEMA_PATH = Path(
    "generated/harness/protocol/atlas-harness.schema.json"
)
TYPESCRIPT_PATH = Path(
    "generated/harness/protocol/atlas-harness.d.ts"
)
MANIFEST_PATH = Path("docs/harness/generated-artifacts.json")
MANAGED_PATHS = (SCHEMA_PATH, TYPESCRIPT_PATH, MANIFEST_PATH)
PROTOCOL_MODELS: tuple[type[BaseModel], ...] = (
    CommandEnvelope,
    CommandContract,
    EventRecord,
    PrincipalRecord,
    GrantRecord,
    WorkspaceRecord,
    PolicyDecisionRecord,
    ThreadRecord,
    TurnRecord,
    ItemRecord,
    ContextManifest,
    OperationRecord,
    ApprovalRecord,
    ArtifactRecord,
    TaskNodeRecord,
    ProviderRouteDecisionRecord,
    EvaluationRunRecord,
    PageInfo,
)


class ProtocolGenerationError(RuntimeError):
    """Raised when deterministic contract generation cannot complete."""


def _json_bytes(document: object) -> bytes:
    serialized = json.dumps(
        document,
        ensure_ascii=False,
        indent=2,
        sort_keys=True,
    )
    return f"{serialized}\n".encode()


def build_json_schema() -> bytes:
    model_inputs = [(model, "validation") for model in PROTOCOL_MODELS]
    model_references, combined_schema = models_json_schema(
        model_inputs,
        title="Atlas Harness Protocol",
    )
    roots = {
        model.__name__: model_references[(model, "validation")]
        for model in PROTOCOL_MODELS
    }
    definitions = combined_schema.get("$defs")
    if not isinstance(definitions, dict):
        raise ProtocolGenerationError("Pydantic omitted protocol definitions")
    command_contracts = [
        contract.model_dump(mode="json")
        for contract in COMMAND_CONTRACTS
    ]
    document = {
        "$comment": GENERATOR_MARKER,
        "$defs": definitions,
        "$id": f"urn:atlas:harness:protocol:{CURRENT_SCHEMA_VERSION}",
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": False,
        "title": "Atlas Harness Protocol",
        "type": "object",
        "x-atlas-canonical-events": [
            event_type.value for event_type in CanonicalEventType
        ],
        "x-atlas-command-contracts": command_contracts,
        "x-atlas-root-models": roots,
        "x-atlas-schema-version": CURRENT_SCHEMA_VERSION,
    }
    return _json_bytes(document)


def build_typescript(schema_content: bytes) -> bytes:
    command = ["node", "scripts/generate_harness_types.mjs"]
    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            input=schema_content,
            check=False,
            capture_output=True,
            timeout=60,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise ProtocolGenerationError(
            f"TypeScript generator could not run: {error}"
        ) from error
    if completed.returncode != 0:
        stderr = completed.stderr.decode(errors="replace").strip()
        raise ProtocolGenerationError(
            f"TypeScript generator failed: {stderr}"
        )
    output = completed.stdout.replace(b"\r\n", b"\n")
    if not output.endswith(b"\n"):
        output += b"\n"
    if b"Generated by scripts/generate_harness_protocol.py" not in output[:512]:
        raise ProtocolGenerationError("TypeScript output lacks generator marker")
    if b" any" in output or b": any" in output:
        raise ProtocolGenerationError("TypeScript output contains unsafe any")
    if b"[k: string]" in output:
        raise ProtocolGenerationError("TypeScript output contains an open index")
    return output


def _artifact_manifest(outputs: Mapping[Path, bytes]) -> bytes:
    artifact_specs = (
        (
            SCHEMA_PATH,
            GENERATOR_MARKER,
            "pydantic-models-json-schema",
        ),
        (
            TYPESCRIPT_PATH,
            "Generated by scripts/generate_harness_protocol.py",
            GENERATOR_VERSION,
        ),
    )
    artifacts: list[dict[str, str]] = []
    for path, marker, generator in artifact_specs:
        content = outputs[path]
        artifacts.append(
            {
                "generator": generator,
                "marker": marker,
                "path": path.as_posix(),
                "sha256": hashlib.sha256(content).hexdigest(),
            }
        )
    return _json_bytes({"artifacts": artifacts, "schema_version": 1})


def generate_into(output_root: Path) -> None:
    schema_content = build_json_schema()
    typescript_content = build_typescript(schema_content)
    outputs = {
        SCHEMA_PATH: schema_content,
        TYPESCRIPT_PATH: typescript_content,
    }
    outputs[MANIFEST_PATH] = _artifact_manifest(outputs)
    for relative_path, content in outputs.items():
        destination = output_root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(content)


def synchronize(*, write: bool) -> None:
    with tempfile.TemporaryDirectory(prefix="atlas-harness-protocol-") as raw:
        temporary_root = Path(raw)
        generate_into(temporary_root)
        differences: list[str] = []
        for relative_path in MANAGED_PATHS:
            generated_path = temporary_root / relative_path
            checked_in_path = ROOT / relative_path
            if write:
                checked_in_path.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(generated_path, checked_in_path)
                continue
            if not checked_in_path.is_file():
                differences.append(f"missing {relative_path.as_posix()}")
                continue
            if checked_in_path.read_bytes() != generated_path.read_bytes():
                differences.append(f"changed {relative_path.as_posix()}")
        if differences:
            joined = ", ".join(differences)
            raise ProtocolGenerationError(
                f"generated protocol artifacts are stale: {joined}"
            )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    try:
        synchronize(write=arguments.write)
    except ProtocolGenerationError as error:
        print(f"Protocol generation failed: {error}", file=sys.stderr)
        return 1
    action = "generated" if arguments.write else "verified"
    print(
        f"Protocol artifacts {action}: schema {CURRENT_SCHEMA_VERSION}, "
        f"{len(PROTOCOL_MODELS)} roots"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
